networks:
  ReverseProxy:
    external: true
  gitea:
    external: false

services:
  db:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

  server:
    image: docker.io/gitea/gitea:1.23-nightly
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - ReverseProxy
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    labels:
      - traefik.http.routers.server.rule=Host(`gitea.docker.localhost`)
      - traefik.http.services.server.loadbalancer.server.port=3000
      # - traefik.http.routers.server.tls=true
      # - traefik.http.routers.server.tls.certresolver=myresolver
      # - traefik.http.routers.server.tls.domains[0].main=gitea.docker.localhost

  # runner:
  #   image: gitea/act_runner:nightly
  #   container_name: gitea-docker-runner
  #   environment:
  #     CONFIG_FILE: /config.yaml
  #     GITEA_INSTANCE_URL: http://host.docker.internal:3000
  #     GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
  #     GITEA_RUNNER_NAME: gitea-runner
  #     GITEA_RUNNER_LABELS: gitea-runner
  #   volumes:
  #     - ./config.yaml:/config.yaml
  #     - ./data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - server

